azure:
  connection_string: "your_connection_string"
  container_name: "wikipedia-data"
  batch_size: 1000

naming:
  file_pattern: "article_{index:06d}.json"
  directory_pattern: "batch_{batch_num:03d}"

api:
  base_url: "https://en.wikipedia.org/w/api.php"
  user_agent: "WikipediaDataPipeline/1.0"
  max_retries: 3
  initial_delay: 1
  max_delay: 60

# Content format options: 'wikitext', 'html', 'plain'
content:
  preferred_format: "wikitext"
  include_parsed_content: true
  use_enhanced_libraries: true
  fallback_to_basic_api: true

logging:
  level: "INFO"
  main_log: "logs/wiki_pipeline.log"
  error_log: "logs/errors.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5

processing:
  batch_size: 1000
  checkpoint_interval: 100
  queue_persistence: true 